---
title: "Curso de R básico"
author: "Sergio Pedro R Oliveira"
date: "`r Sys.Date()`"
output:
  md_document:
    number_sections: true
    variant: markdown_github
  html_document:
    number_sections: true
    df_print: paged
  word_document:
    toc: TRUE
    number_sections: true
  github_document: default
  pdf_document:
    number_sections: true
    toc: TRUE
  odt_document:
    number_sections: true
---

# Objetivo

Estudo dirigido de básico de linguagem R.\

# Referência

Videoaulas de 'curso R para iniciantes'.\

\newpage

# Aula 01 - Introdução

- **R** é uma linguagem estatística e gráfica.\
- É uma linguagem com um foco bem definido.\
- Muito usada para **Big Data** e **Machine Learning**.\
- Linguagem de codigo aberto.\
- Muitos pacotes a disposição.\
- Ambiente de desenvolvimento: **RStudio**.\

\newpage

# Aula 02 - Instalação R e RStudio

- **R**\
<https://cran.r-project.org/> \

- **RStudio**(IDE)\
<https://www.rstudio.com/> \

\newpage

# Aula 03 - Conhecendo o R e o RStudio parte 1

## Configuração do **layout** do **RStudio**

- Alterando o *layout* do **RStudio**:\
  - opção **Tools**\
  - **Global Options**\
  - **Pane Layout**\
  Reorganizar o *layout* das janelas do RStudio para melhor se adaptar ao usuário.\

## Inserir **comentarios**
- Inserir **comentarios**, utilizar '**#**'.\

## Compilar codigo
- Para executar um script:\
  - Deixar o cursor sobre a linha que deve ser executada.\
  - Selecionar o codigo que deve ser executado.\
  Obs.: Atalho para executar 'CRTL + Enter'.\

## Limpar a tela do console
- Comando que limpa a tela do console:\
  - **CTRL** + **L**\

## Atribuições
(Tipagem automatica/dinâmica)\

- Atribuições de **variaveis** usar o sinal '**->**' ou '**<-**'.\

- Atribuição de **funções** utilizar o sinal '**=**'.\

## Tipagem de variaveis
- Tipagem das variaveis automatica/dinâmica.\
- Erro ao fazer operações com variaveis de tipos distintos.\
  
\newpage

# Aula 04 - Conhecendo R e o RStudio parte 2

## **Packages** - Bibliotecas/Pacotes
- São bibliotecas/pacotes com funções que podem ser baixados e instalados.\
- Os pacotes/bibliotecas são instalados no sistema.\
- As bibliotecas são baixadas com o comando no **R**:\
  - Sintaxe:\
  **install**.**packages** ("*nome_do_pacote*")\
- Para usar os pacotes é preciso declarar eles no script (chamar o pacote):\
  - Sintaxe:\
  **library**("*nome_do_pacote*")\
- Baixado e declarado o pacote/biblioteca no script é possivel agora usar as funções desse pacote.\ 

\newpage

## Pesquisa de função - função Help

- Help '**?**', usado para pesquisar uma função na documentação do **R**.\
- O resultado da pesquisa aparece no *Help*.\
- Sintaxe:\
**?***c*\
- Caso o *Help* não ajude a descobrir a função, outro modo de pesquisar é recorrer ao site:\
<https://www.rdocumentation.org/> \
  - Um site destinado a pesquisa e informações sobre a documentação do **R**.\
  - Retorna informações sobre a função, estrutura, pacote a qual ela faz parte, etc.\

## **summary** - Resumo dos dados
- A função **summary**() retorna o resumo de variaveis.\
- O retorno depende do argumento (se for um vetor, uma lista, um data.table).\
- O retorno da função, no geral, retorna diversos metodos aplicados aos dados, tais como:\
  - valor mínimo\
  - 1º quantil\
  - valor da mediana\
  - valor da media\
  - 3º quantil\
  - valor máximo\
- Sintaxe:\
**summary**(*variavel*)\

## Descobrir a classe de uma variavel - **class**
- A função "**class**()" retorna a que classe do objeto do argemunto pertence.\
- Basicamente diz se o objeto é numerico, string, vetor, lista, data.frame, matriz, ...\
- Sintaxe:\
**class**(*argumento*)\

## Descobrir a estrutura de uma variavel - **str**
- A função "**str**()" retorna a estrutura do objeto do argumento.\
- Retorna diversos dados, entre eles:\
  - A classe do objeto.\
  - Tamanho do objeto.\
  - A lista, ou vertor, dos campos com o tipo e tamanho.\ 
- Sintaxe:\
**str**(*argumento*)\

\newpage

## Vetor

- Vetores são variaves que aguardam diversos valores de mesmo tipo.\
- No **R** o vetor é criado a partir da função "*c*()".\
- *Strings* e *caracteres* dentro do vetor devem ter seus valores entre aspas ("").\
- Sintaxe (exemplo):\
**c**(10,5,8,...)\
  
## Lista

- Listas sao os objetos R que contem elementos de diferentes tipos (diferente do vetor), como _ numeros, strings, vetores e outra lista dentro dela.\
- Uma lista tambem pode conter uma matriz ou uma funcao como seus elementos.\
- *Strings* e *caracteres* dentro da lista devem ter seus valores entre aspas ("").\
- A lista e criada usando a funcao "*list*()".\
- Sintaxe (exemplo):\
**list**(azul, 10, c(5,8,9), ...)\

\newpage

# Aula 05 - Operadores

\newpage

# Aula 06 - 

\newpage

# Aula 07 - 

\newpage

# Aula 08 - 

\newpage

# Aula 09 - 

\newpage

# Aula 10 - 

\newpage

# Aula 11 - 

\newpage

# Aula 12 - 

\newpage

# Aula 13 - 

\newpage

# Aula 14 - 

\newpage

# Aula 15 - 

\newpage

# Aula 16 - 

\newpage

# Aula 17 - 

\newpage

# Andamento dos Estudos

## Assunto em andamento

Atualmente estou escrevendo Aula 05.\
